DROP TABLE IF EXISTS USER ;
CREATE TABLE USER (IdUser BIGINT  AUTO_INCREMENT NOT NULL,
Nom VARCHAR(50),
Pseudo VARCHAR(50),
MDP VARCHAR(100),
Email VARCHAR(100),
Statut INTEGER,
PRIMARY KEY (IdUser) ) ENGINE=InnoDB;

DROP TABLE IF EXISTS ALBUM ;
CREATE TABLE ALBUM (IdAlbum BIGINT  AUTO_INCREMENT NOT NULL,
NomAlbum VARCHAR(50),
NomArtiste VARCHAR(50),
DateParution DATE,
Pochette VARCHAR(100),
IdStyle BIGINT NOT NULL,
PRIMARY KEY (IdAlbum) ) ENGINE=InnoDB;

DROP TABLE IF EXISTS MUSIQUE ;
CREATE TABLE MUSIQUE (IdMusique BIGINT  AUTO_INCREMENT NOT NULL,
Titre VARCHAR(100),
Piste VARCHAR(100),
IdAlbum BIGINT NOT NULL,
PRIMARY KEY (IdMusique) ) ENGINE=InnoDB;

DROP TABLE IF EXISTS STYLE ;
CREATE TABLE STYLE (IdStyle BIGINT  AUTO_INCREMENT NOT NULL,
Style VARCHAR(50),
PRIMARY KEY (IdStyle) ) ENGINE=InnoDB;

DROP TABLE IF EXISTS DEPOSER ;
CREATE TABLE DEPOSER (IdUser BIGINT  AUTO_INCREMENT NOT NULL,
IdMusique BIGINT NOT NULL,
PRIMARY KEY (IdUser,
 IdMusique) ) ENGINE=InnoDB;

ALTER TABLE ALBUM ADD CONSTRAINT FK_ALBUM_IdStyle FOREIGN KEY (IdStyle) REFERENCES STYLE (IdStyle);

ALTER TABLE MUSIQUE ADD CONSTRAINT FK_MUSIQUE_IdAlbum FOREIGN KEY (IdAlbum) REFERENCES ALBUM (IdAlbum);
ALTER TABLE DEPOSER ADD CONSTRAINT FK_DEPOSER_IdUser FOREIGN KEY (IdUser) REFERENCES USER (IdUser);
ALTER TABLE DEPOSER ADD CONSTRAINT FK_DEPOSER_IdMusique FOREIGN KEY (IdMusique) REFERENCES MUSIQUE (IdMusique);
